version: "3"
services:
  application:
    build:
      context: .
    ports:
      - "8000:8009"
    volumes:
      - ./application:/opt/application
    command: >
      sh -c "python manager.py runserver 0.0.0.0:8000"