# Defining the docker compose version '3' is the latest version
version: "3"
# Defining the services list needed to run the our application
services:
  #  First one here is our own custom name of the service can have multiple service names here each have it's own workflow
  application:
    build:
      context: .
    # Port mapping
    ports:
      - "8000:8009"
    # real time directory updates into our docker image
    volumes:
      - ./application:/opt/application
    command: >
      sh -c "python manager.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=django_postgres
      - DB_USER=django_postgres
      - DB_PASS=postgresspass

    depends_on:
      - db


  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=django_postgres
      - POSTGRESS_PASSWORD=postgresspass