# Generated by Django 3.1.7 on 2021-07-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profision',
            new_name='career',
        ),
    ]
